In [1]:
import pandas as pd
import json

In [26]:
import json

data = []
with open("2008-sep-29-detailed-scoreboard.json", "r") as f:
    obj_str = ""
    for line in f:
        obj_str += line
        try:
            obj = json.loads(obj_str)
            data.append(obj)
            obj_str = ""
        except json.JSONDecodeError:
            continue

In [ ]:
data

In [32]:
csv_test = pd.read_csv("sep-29-2008-final-scoreboard-csv.csv")

In [33]:
csv_test

,Unnamed: 0,speaker,content,turn_number,cumulative_speaker_turn_number,word_count_points,sentence_count_points,named_entity_count_points,named_entities,bonus_word_points,...,ethos_score_explained,pathos_score_explained,logos_score_explained,epl_multiplier,total_turn_score,cumulative_speaker_base_score,cumulative_speaker_total_score,E_Expl,P_Expl,L_Expl
0,0,LEHRER,Good evening from the Ford Center for the Perf...,1,1,291,16,30,"(evening, the Ford Center for the Performing A...",132,...,empty,empty,empty,1.583333,742.583333,469,742.583333,The speaker establishes their credibility thro...,There is minimal emotional appeal in the intro...,The speaker uses a well-structured format for ...
1,1,OBAMA,"Well, thank you very much, Jim, and thanks to ...",2,1,484,19,14,"(Jim, the University of Mississippi, tonight, ...",173,...,empty,empty,empty,1.733333,1196.000000,690,1196.000000,The speaker establishes credibility by thankin...,The speaker appeals to emotions by addressing ...,The speaker uses a logical approach by present...
2,2,LEHRER,"Senator McCain, two minutes.",3,2,6,1,2,"(McCain, two minutes)",2,...,empty,empty,empty,1.000000,11.000000,480,753.583333,NaN,NaN,NaN
3,3,MCCAIN,"Well, thank you, Jim. And thanks to everybody....",4,1,472,28,27,"(Jim, tonight, Kennedy, Senate, the University...",149,...,empty,empty,empty,1.750000,1183.000000,676,1183.000000,The speaker references their own experience an...,The speaker connects Americans' fears and conc...,The speech provides logical reasoning for crea...
4,4,LEHRER,"All right, let’s go back to my question. How d...",5,3,79,7,4,"(’s, five minutes, Obama, McCain)",40,...,empty,empty,empty,1.266667,164.666667,610,918.250000,The speaker mentions being able to negotiate a...,The speaker attempts to create a sense of urge...,The snippet contains logical elements with ask...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,372,MCCAIN,"I’ve been involved, as I mentioned to you befo...",373,125,312,15,6,"(20-some years, Obama, Russian, Georgia, the U...",113,...,empty,empty,empty,1.793333,799.826667,25679,42349.170000,The speaker effectively establishes credibilit...,The speaker appeals to emotions by expressing ...,The speaker provides logical arguments highlig...
373,373,OBAMA,"Well, let me just make a closing point. You kn...",374,126,220,8,7,"(Kenya, the United States, Earth, the United S...",96,...,empty,empty,empty,1.723333,570.423333,27444,47218.810000,The speaker establishes credibility by sharing...,The snippet invokes emotions by discussing how...,The speaker provides a logical argument for in...
374,374,LEHRER,Few seconds. We’re almost finished.,375,124,9,2,0,(),5,...,empty,empty,empty,1.000000,16.000000,5607,7328.286667,NaN,NaN,NaN
375,375,MCCAIN,"Jim, when I came home from prison, I saw our v...",376,126,107,3,4,"(Jim, MIA, two, the United States)",55,...,empty,empty,empty,1.733333,292.933333,25848,42642.103333,The speaker establishes credibility by mention...,The speaker invokes sadness in their experienc...,The speaker provides examples of their work on...
376,376,LEHRER,And that ends this debate tonight. On October ...,377,125,78,7,13,"(tonight, October 2nd, next Thursday, 9:00 p.m...",41,...,empty,empty,empty,1.260000,175.140000,5746,7503.426667,"The moderator, Jim Lehrer references his PBS c...",NaN,NaN

In [ ]:
df['content'] = df['choices'].apply(lambda x: x[0]['message']['content'])

In [21]:
df['content'] = df['content'].apply(json.loads)

In [24]:
df = df[['content']]

In [25]:
df

                                               content
0    {'E': 0.0, 'P': 0.0, 'L': 0.0, 'E_Expl': '', '...
1    {'E': 0.0, 'P': 0.0, 'L': 0.0, 'E_Expl': '', '...
2    {'E': 0.0, 'P': 7.5, 'L': 0.0, 'E_Expl': '', '...
3    {'E': 0.0, 'P': 0.0, 'L': 0.0, 'E_Expl': '', '...
4    {'E': 0.0, 'P': 0.0, 'L': 0.0, 'E_Expl': '', '...
..                                                 ...
461  {'E': 0.0, 'P': 0.0, 'L': 0.0, 'E_Expl': '', '...
462  {'E': 0.0, 'P': 0.0, 'L': 0.0, 'E_Expl': '', '...
463  {'E': 0.0, 'P': 1.7, 'L': 0.0, 'E_Expl': '', '...
464  {'E': 0.0, 'P': 0.0, 'L': 0.0, 'E_Expl': '', '...
465  {'E': 5.5, 'P': 7.5, 'L': 2.0, 'E_Expl': 'The ...

[466 rows x 1 columns]